### PR TITLE
Moving Bellbot to strands_hri

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@cdondrup as this is "your" repo, you shall have your last famous words...

**Comment by cdondrup** [comment]
Thank you for this opportunity :)
There are a few issues with this: 
- atm, none of the packages defines an install target, so releasing won't be an option. 
- Several dependencies are not correctly defined, i.e. missing from the package.xml and CMakeLists.txt. 
- The feedback service is just empty and could be substituted with `std_srvs/Empty`.
- And since I just glanced over it, there might be some other things missing or incorrect like the incorrect version numbers in the package.xml files, etc.

Since @Jailander is quite busy, I know this won't be fixed soon. So if someone wants to work on this and needs it merged before the issues are fixed, my famous last words would be:
"Sure, just merge it. What's the worst that can happen?"

**Comment by Jailander** [comment]
I can fix the feedback service I just need to delete the file is not needed anymore, for the rest if no one else volunteers I'll leave it for my next week's todo list

**Comment by RaresAmbrus** [comment]
@Jailander I can help you with that, but as you say - it's for next week's todo list.

**Comment by Jailander** [comment]
Thank you @RaresAmbrus you are the best!!

**Comment by marc-hanheide** [comment]
Well, then let's merge it for now, but I shall chase you about this ;-)

**Pull request merged**
