### PR TITLE
Annotation tool for people trajectories

### PR DESCRIPTION
**Pull request by cdondrup**
This tool allows to define classes in the yaml file as buttons which can then be used to label trajectories.
screenshot from 2016-07-18 21 02 26

The lines are drawn sequentially so show the direction of movement. Robot in blue and human in red.

Currently is only played once. Use the back `<` and foward `>` button to reply. Once a button is pressed the result is saved in the database in the new collection `people_perception_annotations` (default value that can be changed).

Options are:

```
positional arguments:
  config                Path to yaml config file

optional arguments:
  -h, --help            show this help message and exit
  --dbhost DBHOST       The database host IP.
  --dbport DBPORT       The database port
  --db DB               The database name
  --data_collection DATA_COLLECTION
                        The collection in the database db that contains the
                        people tracks
  --annotation_collection ANNOTATION_COLLECTION
                        The collection in the database db that should contain
                        the results
  --min_num_entries MIN_NUM_ENTRIES
                        The minimum number of entries per uuid to be
                        considered for annotation
  --min_min_dist MIN_MIN_DIST
                        The minimum minimum distance of the human to the robot
                        for a uuid to be considered for annotation
  --min_travel_dist MIN_TRAVEL_DIST
                        The minimum travel distance accumulated over all poses
                        of human and robot for a uuid to be considered for
                        annotation

```

Not pretty but should hopefully do the trick.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
What's a good parameter to get a meaningful number of trajectories to annotate? How many do the defaults return for AAF y3?

**Comment by cdondrup** [comment]
Good question didn't try yet. It doesn't work with queuing really for the min dist and travel dist. I can have a look tomorrow.

**Comment by hawesie** [comment]
I think there is an overlap between this and some things that @ferdianjovan did previously in SOMa. I'm just tagging him here in case there's something worth discussing.

**Comment by cdondrup** [comment]
Didn't know... only took me half a day though... Not much harm done ;)

Edit: And I learned how to use pymongo... horrible stuff.

**Comment by cdondrup** [comment]
Added a script that creates csv files for the offline qtc creator from the annotations and the corresponding data in the DB.

Almost the same command line options as the annotation tool:

```
$ ./create_csv.py -h
usage: create_csv.py [-h] [--dbhost DBHOST] [--dbport DBPORT] [--db DB]
                     [--data_collection DATA_COLLECTION]
                     [--annotation_collection ANNOTATION_COLLECTION]
                     config save_path

positional arguments:
  config                Path to yaml config file
  save_path             Path to save the csv files under. Naming scheme:
                        uuid.csv. Creates directories for each class found.

optional arguments:
  -h, --help            show this help message and exit
  --dbhost DBHOST       The database host IP.
  --dbport DBPORT       The database port
  --db DB               The database name
  --data_collection DATA_COLLECTION
                        The collection in the database db that contains the
                        people tracks
  --annotation_collection ANNOTATION_COLLECTION
                        The collection in the database db that should contain
                        the results

```

The yaml config file has to be the same as the one used for the annotation tool as it needs to have the same class names in it.

**Comment by cdondrup** [comment]
Updates:

The filtering of people is now done seprately and saved in a new collection. The options for the annotation tool have, therefore, been reduced:

```
$ ./annotation_tool.py -h
usage: annotation_tool.py [-h] [--dbhost DBHOST] [--dbport DBPORT] [--db DB]
                          [--data_collection DATA_COLLECTION]
                          [--annotation_collection ANNOTATION_COLLECTION]
                          config

positional arguments:
  config                Path to yaml config file

optional arguments:
  -h, --help            show this help message and exit
  --dbhost DBHOST       The database host IP.
  --dbport DBPORT       The database port
  --db DB               The database name
  --data_collection DATA_COLLECTION
                        The collection in the database db that contains the
                        people tracks
  --annotation_collection ANNOTATION_COLLECTION
                        The collection in the database db that should contain
                        the results
```

The new script `filter_db_entries.py` has the following options:

```
$ ./filter_db_entries.py -h
usage: filter_db_entries.py [-h] [-f] [-s SAVE_UUIDS] [-l LOAD_UUIDS]
                            [--dbhost DBHOST] [--dbport DBPORT] [--db DB]
                            [--data_collection DATA_COLLECTION]
                            [--filtered_collection FILTERED_COLLECTION]
                            [--min_num_entries MIN_NUM_ENTRIES]
                            [--min_min_dist MIN_MIN_DIST]
                            [--min_travel_dist MIN_TRAVEL_DIST]

optional arguments:
  -h, --help            show this help message and exit
  -f, --force           If collection already exists, it will be dropped first
                        to force override.
  -s SAVE_UUIDS, --save_uuids SAVE_UUIDS
                        Specify a file to save the list of distinct uuids in.
                        Yaml format.
  -l LOAD_UUIDS, --load_uuids LOAD_UUIDS
                        Specify a file to load the list of distinct uuids from
                        to prevent parsing the DB. Yaml format.
  --dbhost DBHOST       The database host IP.
  --dbport DBPORT       The database port
  --db DB               The database name
  --data_collection DATA_COLLECTION
                        The collection in the database db that contains the
                        people tracks
  --filtered_collection FILTERED_COLLECTION
                        The collection in the database db that should contain
                        the results
  --min_num_entries MIN_NUM_ENTRIES
                        The minimum number of entries per uuid to be
                        considered for annotation
  --min_min_dist MIN_MIN_DIST
                        The minimum minimum distance of the human to the robot
                        for a uuid to be considered for annotation
  --min_travel_dist MIN_TRAVEL_DIST
                        The minimum travel distance accumulated over all poses
                        of human and robot for a uuid to be considered for
                        annotation

```

It creates a new collection with all the people tracks that conform with the filter settings. this new collection is by default used by the annotation tool. The default values seem to produce decent results for the AAf y3 dataset.

**Comment by ferdianjovan** [comment]
This is better because this shows movie-like trajectories whereas what we have atm is just for visualisation. Thanks @cdondrup

**Pull request merged**
