### PR TITLE
Adding the custom dynamic reconfigure parameters to human_aware wrapper.

### PR DESCRIPTION
**Pull request by cdondrup**
@lucasb-eyer to test

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
did we test/what's the state @bfalacerda ?

**Comment by cdondrup** [comment]
Yes, and it didn't work properly. Have to test this at home. For now we are just not using the dwa wrapper for now.

**Comment by marc-hanheide** [comment]
Are you going to fix it or close it?

**Comment by cdondrup** [comment]
Still didn't test it to find the error... oops. Will try and fix it early next week.

**Comment by cdondrup** [comment]
I'm doing something nasty with namespaces in that node. Now it works for me and sets the correct parameters. Maybe @bfalacerda or @lucasb-eyer have time to check that it really sets the `site_move_base_parameters` correctly.

**Comment by marc-hanheide** [comment]
anyone tested this?

**Comment by lucasb-eyer** [comment]
No, I don't have the time to test it until in about a month... sorry :-/

**Comment by cdondrup** [comment]
Damn, I didn't want to push the latest commit to this... But only a minor change so shouldn't do any harm.

**Comment by cdondrup** [comment]
Due to the holiday season and no one having time, and since this is not critical any more and doesn't work properly as it is now, I will merge this if no one objects. It works for me and also you can't break anything that is already broken.

**Comment by lucasb-eyer** [comment]
I'm OK with this

**Pull request merged**
