### PR TITLE
using arrows for direction and feedback question in German

### PR DESCRIPTION
**Pull request by marc-hanheide**
apologies, but the files where in such a mess re indentation, that I had to reformat some of it. I also restructured the very static HTML to work for different numbers of questions... so, quite many changes, but nothing that effects the general logic.

### CODE REVIEW

**Comment by cdondrup** [comment]
- The going back to start page is missing the arrows.
- The feedback should be stored in the datacentre directly.

**Comment by marc-hanheide** [comment]
I have added the two things now. Tested locally.

**Comment by marc-hanheide** [comment]
I'm finished with this PR, so it could be merged if you agree.

**Comment by cdondrup** [comment]
I do.

**Pull request merged**
