### PR TITLE
[hrsi_representation] Adding correct smoothing and unittest

### PR DESCRIPTION
**Pull request by cdondrup**
As the title says, this adds a unittest and improvements to everything that proved to be faulty running the unittest.

**Smoothing**: Has been done via a simple sleep, now handled correctly by creating the mean over the poses received during the smoothing interval

**Decay**: Now uses the message times instead of `time.now` which allows to use this on bags and the live system. Since the ppl tracker publishes continuously, this shouldn't present a problem. Decay is not a vital function in the first place anyway.

**General processing**: The qsr_lib qtc request is too slow to work in real-time let alone with sped up bag replay. Therefore, the processing has been moved to a separate thread which runs at 30Hz by default (60Hz for the sped up test)

### CODE REVIEW

**Comment by cdondrup** [comment]
The test passed but maybe @marc-hanheide  can have a look if it is in the right location or if my test are flawed in general.

**Comment by marc-hanheide** [comment]
nope... I think I found the culprit: https://github.com/ros/catkin/pull/728 ... they have destroyed our setup by changing catkin and rostest
see also https://github.com/ros/ros_comm/pull/611

**Comment by cdondrup** [comment]
Again a patch that breaks our system... But at least it's not my fault 😁

**Comment by cdondrup** [comment]
Is this OK to merge then? No one uses this so far and the test passes.

**Pull request merged**
