### PR TITLE
Add another simple human following

### PR DESCRIPTION
**Pull request by ferdianjovan**
Hi,

This is our simple human following. I am not sure the package works perfectly as the problem with /ptu/state has not been solved here. It would be good if someone could try on their robots.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
this depends on something that cannot be resolved or is not released: 

```
KeyError: 'nav_goals_msgs'
```

**Comment by cdondrup** [comment]
The launch file also includes the `nav_goals_generator` and as @marc-hanheide said, the `nav_goals_msgs`, which are both in `strands_utils`. In general we can merge this since we have a few packages in here that are not released anyway but if you, @ferdianjovan want to have this released, you would need to move the two packages this depends on to `strands_navigation` or another fitting repository.
Also please check the dependencies in the package.xml. The `nav_goals_generator` seems to be missing. Maybe something else is also amiss.

In general I'm happy to merge this but please let me know if you want this released or not. If so, the above things have to be fixed before the merge.

**Comment by cdondrup** [comment]
For some reason I mistook this for the people perception repository... Since this repository does not have a release branch and I'm not really keen on maintaining one, it would be nice if you could take care of the above issue, @ferdianjovan before this is merged.

**Comment by ferdianjovan** [comment]
I would like this to be released. I will fix the problem today.

**Comment by cdondrup** [comment]
Still needs the `nav_goal_generator` and `nav_goal_msgs` to be released first:
`KeyError: 'nav_goals_generator'`

**Comment by cdondrup** [comment]
Oh, you removed the `nav_goals_msgs`... So only the generator has to be released first.

**Comment by ferdianjovan** [comment]
I need to try the nav_goals_generator which is inside strands_navigation as you suggested.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
there was a network error on the build server, so I triggered it to try again

**Comment by cdondrup** [comment]
Shouldn't work because the PR for the nav_goals_generator in strands_navigation is not yet merged nor released.

**Comment by marc-hanheide** [comment]
yes, but the failure it reported here was still a wrong one, now it's at least failing for the right reason ;-)

**Comment by kunzel** [comment]
@marc-hanheide, @cdondrup Is there still a problem with this package? Can it be merged? Or what should we ( @ferdianjovan) do? Thanks!

**Comment by marc-hanheide** [comment]
we just have to wait for the new strands_navigation to be released (ongoing)

**Comment by ferdianjovan** [comment]
Just got the email from Jenkins, apparently nav_goals_generator are not in released package.

**Comment by marc-hanheide** [comment]
but they will be soon

**Comment by marc-hanheide** [comment]
release of strands_navigation is underway: https://github.com/strands-project/rosdistro/pull/188 After this, we can run another test

**Comment by marc-hanheide** [comment]
test this please

**Comment by marc-hanheide** [comment]
Finally compiles. @cdondrup should have the last say in this.

**Comment by cdondrup** [comment]
Looks fine. I'll merge and start the release.

**Pull request merged**
