### PR TITLE
Adding ability of reconfiguring movebase and human_aware together

### LINKED ISSUE #86: human_aware_navigation.py uses hardcoded fast parameters
These should be configurable in some way.

### PR DESCRIPTION
**Pull request by cdondrup**
Problem description: the parameters in human_aware_navigation where "hard coded" (only updated from param server when restarted) due to a particular error of dynamic reconfigure. Sometimes it fails for no obvious reason and there is no use in retrying it since it fails continuously. In such cases the speed would not have been reset properly and at the next node when updating the default max speeds, the human_aware would take the lower ones and never recover to the full speed. Hence #86.

Arising problem due to new features in navigation: the speed can now (or soon) be defined on edges in the topo map. This would need to reconfigure move_base. This would rob it of the flexibility of replacing the move_base action with human_aware_navigation on edges because it would still try to reconfigure move_base but not human_aware. There now is a very ugly node, didn't find a better solution (only one dyn calback in python, no namspaces in python), that works on `/human_aware_navigation/DWAPlannerROS` and then reconfigures `/move_base/DWAPlannerROS` and human_aware_navigation itself. Therefore, topo nav can now rely on on `<move_action>/DWAPlannerROS` to be reconfigurable.

closes #86

### CODE REVIEW

**Comment by Jailander** [comment]
Awesome will start testing it now :)

**Comment by marc-hanheide** [comment]
I'm unable to assess all the side effects of all these changes. I need somebody to tell me it's OK before I can merge the whole related bundle of PRs.

**Comment by hawesie** [comment]
I think we need feedback from people running robots

**Comment by Jailander** [comment]
yes this is not ready to merge yet, it still needs changes in execute policy server I will post a detailed explanation on the commit doing these changes

**Comment by marc-hanheide** [comment]
When will it be?

**Comment by Jailander** [comment]
Now... waiting to hear on https://github.com/strands-project/strands_navigation/pull/234 but it works for me

**Comment by cdondrup** [comment]
https://github.com/strands-project/strands_navigation/pull/234 has been merged.
Merging this to have stable system.

**Pull request merged**
