### PR TITLE
syncing and gui2 in progress

### PR DESCRIPTION
**Pull request by gatsoulis**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
if this is "in progress", then I shall not yet merge it, right?

**Comment by gatsoulis** [comment]
@marc-hanheide as you wish... we are syncing from each other's repo at the moment (at least me and @Jailander), and to be honest the version on upstream is "incomplete and buggy" which most do not exist on this pull request (at least for one of the modes) + several improvements including HRI features that @denisehe has requested... can go into details on monday's meeting.

ps: i really hope that onboard virtual keyboard can be used on the robot otherwise :(

**Comment by gatsoulis** [comment]
@marc-hanheide one last thing i forgot, bear in mind that somethings that should go to aaf_deployment are at the moment in here... referring to a few files in the www folder... hope it's not a major problem for now.

**Comment by cdondrup** [comment]
Regarding the upstream being buggy, please make sure it builds and installs before you merge anything. Otherwise you can always use a branch.

**Comment by gatsoulis** [comment]
@cdondrup by upstream I was referring to the strands/strands_hri repo... btw speaking about branches... the branch for strands_hri is hydro... shouldn't there be an indigo one?

**Comment by marc-hanheide** [comment]
@yianni the branch's name is "hydro", doesn't mean it doesn't work for indigo. We have the policy to not introduce additional branches if not needed. Hence, we stick to this one for now.

For the keyboard: If you GUI needs a keyboard, then that's not a problem. There are plenty of javascript keyboard out there that are easily integrated. The Ubuntu on board one is definitely not an option. We cannot programmatically (un-)display it. And we certainly cannot have a keyboard constantly covering the  screen. If you need a keyboard, use a javascript one that you embed into the web page. That's not hard to do at all.

**Comment by gatsoulis** [comment]
@marc-hanheide thanks for the clarification about the branch naming. On lucie that I tried it onboard has an option of auto-hiding when there is no text input, but regardless I will have a look on javascript keyboards that can be embedded.

**Comment by marc-hanheide** [comment]
So, your call if we should merge this for now or not, @yianni. As long as it doesn't break our builds I don't mind merging it. But if it's not needed right now I'm reluctant to merge something half-working/untested and would prefer to close this unmerged

**Comment by gatsoulis** [comment]
No prob. Go ahead and reject the pull.

**Pull request closed without merging**
