### PR TITLE
0.0.7

### PR DESCRIPTION
**Pull request by gatsoulis**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
It's far beyond me to assess if this all makes sense :smirk: but I have to assume so. We are going to properly test this tomorrow, I suppose.

**Comment by marc-hanheide** [comment]
As this only effects bellbot, I shall merge now.

**Comment by cdondrup** [comment]
This has all the same issues I mentioned in #100.
This will never work as intended. Needs a lot of fixing I'm afraid.

**Comment by gatsoulis** [comment]
Thanks. I will look into tidying up properly the bellbot repos when I get back.

**Pull request merged**
